/// Flutter icons ButtonIcons
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  ButtonIcons
///      fonts:
///       - asset: fonts/ButtonIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class ButtonIcons {
  ButtonIcons._();

  static const _kFontFam = 'ButtonIcons';

  static const IconData group_13 = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData group_14 = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData ic_people_24px = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData ic_star_24px = const IconData(0xe806, fontFamily: _kFontFam);
}
